fix: 🐛 change end time for day and week view #298
SimformSolutionsPvtLtd/flutter_calendar_view pull request #354
Opened 2024-05-02 09:03 UTC by apurva010

- Added end time support for day and weeek view to set end time of day and week.

# Description

## Checklist

- [x] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [x] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [x] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [x] No, this PR is not a breaking change.

## Related Issues

Closes #298 

[Contributor Guide]: https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/blob/master/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org

2024-05-02 11:59 UTC, vatsaltanna-simformsolutions commented on lib/src/day_view/day_view.dart
> +    _endHour = widget.endHour ?? 24;
use constant file value here

2024-05-02 12:00 UTC, vatsaltanna-simformsolutions commented on lib/src/week_view/week_view.dart
> +    _endHour = widget.endHour ?? 24;
^^

2024-05-02 12:00 UTC, vatsaltanna-simformsolutions commented on lib/src/week_view/week_view.dart
> +    if (_endHour >= 24 || _startHour > _endHour) _endHour = 24;
^^

2024-05-06 10:12 UTC, PRBaraiya requested changes

2024-05-06 10:12 UTC, PRBaraiya commented on README.md
> +    startHour: 51 // To set the first hour displayed (ex: 05:00)
Make this 5.

2024-05-06 10:12 UTC, PRBaraiya commented on lib/src/components/_internal_components.dart
> +    required this.endHour,
This should not be required. set default values for start and end hour.

2024-05-06 10:12 UTC, PRBaraiya commented on lib/src/components/_internal_components.dart
> +    required this.endHour,
Also, add an assert condition to check start hour is not >= then end hour.

2024-05-06 10:12 UTC, PRBaraiya commented on lib/src/day_view/day_view.dart
> +  final int? endHour;
No need to make this nullable. Set default value to 24 hrs.

2024-05-06 10:12 UTC, PRBaraiya commented on lib/src/day_view/day_view.dart
> +  final int? endHour;
Make same changes for start hour as well.

2024-05-06 10:12 UTC, PRBaraiya commented on lib/src/painters.dart
> +    required this.endHour,
remove required and set default value.

2024-05-08 10:51 UTC, vatsaltanna-simformsolutions approved these changes

2024-05-08 10:54 UTC, merged