Feature/custom strings
SimformSolutionsPvtLtd/flutter_calendar_view pull request #36
Opened 2022-02-14 07:44 UTC by b-scharbau

Added StringProvider as optional parameters to the DayView() widget to allow for customization of the time and date display.

Please let me know if you need any additional fixes there

2022-03-14 03:47 UTC, PRBaraiya requested changes

2022-03-14 03:47 UTC, PRBaraiya commented on lib/src/components/day_view_components.dart
> +  final StringProvider timeStringBuilder;
Make this parameter nullable.

2022-03-14 03:47 UTC, PRBaraiya commented on lib/src/components/day_view_components.dart
> +    required this.timeStringBuilder,
Make this optional.

2022-03-14 03:47 UTC, PRBaraiya commented on lib/src/components/day_view_components.dart
> +          timeStringBuilder(date),
Check for null condition here. and use previous format if timeStringBuilder is null.

2022-03-14 03:47 UTC, PRBaraiya commented on lib/src/day_view/day_view.dart
> +      timeStringBuilder: widget.timeStringBuilder ??
remove this null check from here.

2022-03-14 03:48 UTC, PRBaraiya commented
@b-scharbau  Thanks for raising this PR. I have requested some changes in this PR please review them.

2022-06-28 07:20 UTC, b-scharbau commented
Sorry for late response, I was actually busy with other projects and didn't find the time to look after the requested changes.
Updated the code accordingly, please review

2022-07-26 05:03 UTC, PRBaraiya approved these changes

2022-07-30 10:18 UTC, merged