Fix/issue 361 mannuly update scroll offset
SimformSolutionsPvtLtd/flutter_calendar_view pull request #393
Opened 2024-07-24 13:06 UTC by bawantha

# Description

## Checklist

- [ ] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [ ] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [ ] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [ ] No, this PR is not a breaking change.

## Related Issues

[Contributor Guide]: https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/blob/master/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org

2024-09-13 20:23 UTC, ParthBaraiya approved these changes

2024-09-13 20:25 UTC, ParthBaraiya requested changes

2024-09-13 20:25 UTC, ParthBaraiya commented on lib/src/week_view/week_view.dart
> +      _lastScrollOffset = widget.scrollOffset;
This line should be like following,

 _lastScrollOffset = widget.scrollOffset ??
        widget.startDuration.inMinutes * widget.heightPerMinute;

2025-01-02 16:11 UTC, PRBaraiya approved these changes
LGTM!

2025-01-02 16:11 UTC, merged