Feature/reoccurrence event
SimformSolutionsPvtLtd/flutter_calendar_view pull request #415
Opened 2024-10-25 07:28 UTC by shubham-jitiya-simform

# Description

## Checklist

- [ ] The title of my PR starts with a [Conventional Commit] prefix (`fix:`, `feat:`, `docs:` etc).
- [ ] I have followed the [Contributor Guide] when preparing my PR.
- [ ] I have updated/added tests for ALL new/updated/fixed functionality.
- [ ] I have updated/added relevant documentation in `docs` and added dartdoc comments with `///`.
- [x] I have updated/added relevant examples in `examples` or `docs`.

## Breaking Change?

- [ ] Yes, this PR is a breaking change.
- [ ] No, this PR is not a breaking change.

## Related Issues

[Contributor Guide]: https://github.com/SimformSolutionsPvtLtd/flutter_calendar_view/blob/master/CONTRIBUTING.md
[Conventional Commit]: https://conventionalcommits.org

2025-01-02 06:37 UTC, PRBaraiya requested changes

2025-01-02 06:37 UTC, PRBaraiya commented on lib/src/month_view/month_view.dart
> +              hideDaysNotInMonth && (monthDays[index].month != date.month)
What's the reason for changing this?

2025-01-02 06:37 UTC, PRBaraiya commented on lib/src/event_controller.dart
> +  //#region Private Methods
Helper / Private methods must be at the end of the class.

2025-01-02 06:37 UTC, PRBaraiya commented on lib/src/event_controller.dart
> +    event.recurrenceSettings == null
This will add event in _fullDayEventList as well as _reccurringEventsList. Which will create duplication.

2025-01-02 06:37 UTC, PRBaraiya commented on lib/src/event_controller.dart
> +    event.recurrenceSettings == null
^^

2025-01-02 06:37 UTC, PRBaraiya commented on lib/src/event_controller.dart
> +    event.recurrenceSettings == null
^^

2025-01-02 06:37 UTC, PRBaraiya commented on lib/src/event_controller.dart
> +    if (_eventList.contains(event) || _recurringEventsList.contains(event))
No need to check event in _recurringEventsList.

2025-01-02 06:37 UTC, PRBaraiya commented on lib/src/event_controller.dart
> +      event.recurrenceSettings == null
we should be able to remove this in every place as well.

2025-01-02 08:25 UTC, shubham-jitiya-simform commented on lib/src/month_view/month_view.dart
> +              hideDaysNotInMonth && (monthDays[index].month != date.month)
While fixing issue to hide events list in cell if "hide days not in month" is true in PR #422 by mistake bitwise operator `&` is used instead of `&&` AND operator.

2025-01-02 10:37 UTC, shubham-jitiya-simform commented on lib/src/event_controller.dart
> +    event.recurrenceSettings == null
Removed add recurring event in each method addFullDayEvent, addSingleDayEvent & addRangingEvent.

2025-01-03 09:14 UTC, PRBaraiya requested changes

2025-01-03 09:14 UTC, PRBaraiya commented on lib/src/event_controller.dart
> +  UnmodifiableListView<CalendarEventData<T>> get nonRecurringEvents =>
can we keep this as allEvents.

2025-01-03 09:14 UTC, PRBaraiya commented on lib/src/event_controller.dart
> +      _recurringEventsList.add(event);
This should add event in _eventList as well.

2025-01-03 09:14 UTC, PRBaraiya commented on lib/src/event_controller.dart
> +  UnmodifiableListView<CalendarEventData<T>> get recurringEvents =>
Let not add this. It will create confusion.

2025-01-03 11:44 UTC, PRBaraiya approved these changes
LGTM!

2025-01-03 11:47 UTC, merged